apiVersion: v1
kind: Service
metadata:
  name: {{ template "pd0.fullname" . }}
  labels:
    app: {{ template "pd0.name" . }}
    chart: {{ template "pd0.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: http-2379
      protocol: TCP
      name: http-2379
    - port: {{ .Values.service.port2 }}
      targetPort: http-2380
      protocol: TCP
      name: http-2380
  selector:
    app: {{ template "pd0.name" . }}
    release: {{ .Release.Name }}
