data_dir: ./data

pd:
  size: 3
  image: pingcap/pd:latest
  # build from local binary or remote source if image is empty
  buildFrom: local             # local | remote

tikv:
  size: 3
  image: pingcap/tikv:latest
  # build from local binary or remote source if image is empty
  buildFrom: local             # local | remote

tidb:
  image: pingcap/tidb:latest
  # build from local binary or remote source if image is empty
  buildFrom: local             # local | remote
  mysqlPort: "4000"
  statusPort: "10080"

tidbVision:
  image: pingcap/tidb-vision:latest
  # build from local source or remote source if image is empty
  buildFrom: local              # local | remote
  port: "8010"

grafana:
  image: grafana/grafana:4.2.0
  port: "3000"

pushgateway:
  image: prom/pushgateway:v0.3.1

prometheus:
  image: prom/prometheus:v2.0.0
  port: "9090"

dashboardInstaller:
  image: pingcap/tidb-dashboard-installer:v1.0.0
