data_dir: ./data

rustupVersion: 1.7.0
rustToolChain: nightly-2017-08-09

pd:
  size: 3
  image: pingcap/pd:latest
  repo: https://github.com/pingcap/pd.git
  branch: master

tikv:
  size: 3
  image: pingcap/tikv:latest
  repo: https://github.com/pingcap/tikv.git
  branch: master

tidb:
  image: pingcap/tidb:latest
  repo: https://github.com/pingcap/tidb.git
  branch: master
  mysqlPort: "4000"
  statusPort: "10080"

tidbVision:
  # currently there's no such image in DockerHub yet
  # must leave `image` empty and build it from source
  image: pingcap/tidb-vision:latest
  repo: https://github.com/pingcap/tidb-vision.git
  branch: master
  port: "8010"

grafana:
  image: grafana/grafana:4.2.0
  port: "3000"

pushgateway:
  image: prom/pushgateway:v0.3.1

prometheus:
  image: prom/prometheus:v2.0.0
  port: "9090"

dashboardInstaller:
  image: pingcap/tidb-dashboard-installer:v1.0.0
