data_dir: ./data
pd:
  size: 3
  image: pingcap/pd:latest

tikv:
  size: 3
  image: pingcap/tikv:latest

tidb:
  image: pingcap/tidb:latest
  mysqlPort: "4000"
  statusPort: "10080"

grafana:
  image: grafana/grafana:4.2.0
  port: "3000"

pushgateway:
  image: prom/pushgateway:v0.3.1

prometheus:
  image: prom/prometheus:v2.0.0
  port: "9090"

dashboardInstaller:
  image: pingcap/tidb-dashboard-installer:v1.0.0
